apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot
  namespace: default
  labels:
    app: chatbot
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chatbot
  template:
    metadata:
      labels:
        app: chatbot
        version: v1
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: chatbot-sa
      containers:
      - name: chatbot
        image: acrcandidates.azurecr.io/chatbot:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        env:
        - name: REDIS_HOST
          value: "chatbot-x-redis.redis.cache.windows.net"
        - name: REDIS_PORT
          value: "6380"
        - name: OPENAI_ENDPOINT
          value: "https://chatbot-x-openai.openai.azure.com/"
        - name: OPENAI_DEPLOYMENT_NAME
          value: "gpt-4o-mini"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: password
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      imagePullSecrets:
      - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: chatbot-service
  namespace: default
  labels:
    app: chatbot
spec:
  selector:
    app: chatbot
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    name: http
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: chatbot-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: chatbot
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
    scaleUp:
      stabilizationWindowSeconds: 0
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: chatbot-sa
  namespace: default
